version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: php-app
    volumes:
    - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
